# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-25 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20170126_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showgroup',
            name='number',
        ),
        migrations.AddField(
            model_name='showgroup',
            name='file',
            field=models.FileField(default='', upload_to=b''),
            preserve_default=False,
        ),
    ]
