# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-26 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import show.models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_showfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showgroup',
            name='picture',
            field=models.ImageField(upload_to=show.models.upload_path_handler),
        ),
    ]
