# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-28 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_auto_20170126_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showgroup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
