# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-28 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_auto_20170128_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showgroup',
            name='file',
            field=models.FileField(default='', upload_to=b''),
            preserve_default=False,
        ),
    ]
