# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-11 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_showgroup_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='showgroup',
            name='number',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
