# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-27 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_messagefile_before_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home_count',
            field=models.IntegerField(default=0),
        ),
    ]
