# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-25 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20170125_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='file',
            field=models.FileField(default=b'/static/certificate/null.jpg', upload_to=b'static/work/'),
        ),
    ]
