# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-25 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20170125_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='file_uuid',
            new_name='uuid',
        ),
    ]
