# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20170125_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='number',
        ),
        migrations.RemoveField(
            model_name='debug',
            name='number',
        ),
        migrations.AddField(
            model_name='bug',
            name='file',
            field=models.FileField(default='', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debug',
            name='file',
            field=models.FileField(default='', upload_to=b''),
            preserve_default=False,
        ),
    ]
