# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-26 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('fill_time', models.DateTimeField(auto_now_add=True)),
                ('p1', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PreSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('fill_time', models.DateTimeField(auto_now_add=True)),
                ('p1', models.CharField(max_length=128)),
                ('p2', models.CharField(max_length=10)),
            ],
        ),
    ]
